CREATE DATABASE CuaHangVatTu;
USE CuaHangVatTu;

CREATE TABLE PhieuXuat(
SoPX INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NgayXuat DATETIME NOT NULL);

CREATE TABLE VatTu(
MaVatTu INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
TenVatTu VARCHAR(30) NOT NULL
);
 
CREATE TABLE ChiTietPhieuXuat(
DonGX INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
SoLuongXuat INT NOT NULL,
SoPX INT NOT NULL,
MaVatTu INT NOT NULL,
FOREIGN KEY (SoPX) REFERENCES PhieuXuat(SoPX),
FOREIGN KEY (MaVatTu) REFERENCES VatTu(MaVatTu)
); 

CREATE TABLE PhieuNhap(
SoPhieuNhap INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NgayNhap DATETIME NOT NULL
);

CREATE TABLE ChiTietPhieuNhap(
DonGiaNhap INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
SoLuongNhap INT NOT NULL,
SoPhieuNhap INT NOT NULL,
MaVatTu INT NOT NULL,
FOREIGN KEY (SoPhieuNhap) REFERENCES PhieuNhap(SoPhieuNhap),
FOREIGN KEY (MaVatTu) REFERENCES VatTu(MaVatTu)
);

CREATE TABLE NhaCungCap(
MaNCC INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
TenNCC VARCHAR(20) NOT NULL,
DiaChi VARCHAR(20)
);

CREATE TABLE DonDH(
SoDonDH INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NgayDH DATETIME NOT NULL,
MaNCC INT NOT NULL,
FOREIGN KEY (MaNCC) REFERENCES NhaCungCap(MaNCC)
);

CREATE TABLE ChiTietDH(
MaCTDH INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
MaVatTu INT NOT NULL,
SoDonDH INT NOT NULL,
FOREIGN KEY (MaVatTu) REFERENCES VatTu(MaVatTu),
FOREIGN KEY (SoDonDH) REFERENCES DonDH(SoDonDH)
);

CREATE TABLE SoDienThoai(
MaNCC INT NOT NULL,
SDT VARCHAR(20) NOT NULL,
FOREIGN KEY (MaNCC) REFERENCES NhaCungCap(MaNCC)
);







